  server:
  port: 8081
  servlet:
    context-path: /wfy
spring:
  application:
    name: service-provider-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
  management:
    endpoints:
      web:
        base-path: /manage

