package com.service.service.dao;

import com.service.service.model.DeviceModel;

public interface DeviceModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_model
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_model
     *
     * @mbggenerated
     */
    int insert(DeviceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_model
     *
     * @mbggenerated
     */
    int insertSelective(DeviceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_model
     *
     * @mbggenerated
     */
    DeviceModel selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceModel record);
}