package com.service.model;

import java.io.Serializable;
import java.util.Date;

/**
 * @author wfy
 */
public class DeviceModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_model.model_id
     *
     * @mbggenerated
     */

    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_model.model_name
     *
     * @mbggenerated
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_model.model_type
     *
     * @mbggenerated
     */
    private Byte modelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_model.relate_model_id
     *
     * @mbggenerated
     */
    private Integer relateModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_model.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_model.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_model.model_id
     *
     * @return the value of device_model.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_model.model_id
     *
     * @param modelId the value for device_model.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_model.model_name
     *
     * @return the value of device_model.model_name
     *
     * @mbggenerated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_model.model_name
     *
     * @param modelName the value for device_model.model_name
     *
     * @mbggenerated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_model.model_type
     *
     * @return the value of device_model.model_type
     *
     * @mbggenerated
     */
    public Byte getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_model.model_type
     *
     * @param modelType the value for device_model.model_type
     *
     * @mbggenerated
     */
    public void setModelType(Byte modelType) {
        this.modelType = modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_model.relate_model_id
     *
     * @return the value of device_model.relate_model_id
     *
     * @mbggenerated
     */
    public Integer getRelateModelId() {
        return relateModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_model.relate_model_id
     *
     * @param relateModelId the value for device_model.relate_model_id
     *
     * @mbggenerated
     */
    public void setRelateModelId(Integer relateModelId) {
        this.relateModelId = relateModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_model.create_time
     *
     * @return the value of device_model.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_model.create_time
     *
     * @param createTime the value for device_model.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_model.update_time
     *
     * @return the value of device_model.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_model.update_time
     *
     * @param updateTime the value for device_model.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}