server:
  port: 8888

spring:
  application:
    name: config-server-local
  profiles:
    active: local
  cloud:
    config:
      server:
       native:
         search-locations: file:D:\cloud-config


