spring:
   application:
     name: config-server-git
   cloud:
     config:
       server:
          git:
            uri: https://github.com/601021997/spring-cloud-config-repository.git
            username: 601021997
            password: wfy601021997
            default-label: master
   profiles:
     active: git


server:
  port: 8888



